### ISSUE TITLE
Could not find manager _PassThroughManager in model_utils.managers

### ISSUE THREAD

**Issue by pacahon** [carljm/django-model-utils#170]
Hello. I have a problem after migrating from Django 1.7 to 1.8
```
ValueError: Could not find manager _PassThroughManager in model_utils.managers.
Please note that you need to inherit from managers you dynamically generated with 'from_queryset()'.
```
After some debugging I realized, that it happened due to use_in_migrations attribute was added to manager class in Django 1.8
https://docs.djangoproject.com/en/1.8/topics/migrations/#model-managers
>  You can optionally serialize managers into migrations and have them available in RunPython operations

My custom class manager inherited from django.contrib.auth.models.UserManager, where use_in_migrations=True by default and django trying to serialize class instance, but failed:
https://docs.djangoproject.com/en/1.8/topics/migrations/#adding-a-deconstruct-method
> path should be the Python path to the class, with the class name included as the last part (for example, myapp.custom_things.MyClass). If your class is not available at the top level of a module it is not serializable.

Any suggestions how to fix that problem?

**Comment by kezabelle** [comment]
Off the top of my head, as of 1.7+, there's not much of a compelling reason to use `PassThroughManager` over [QuerySet.as_manager](https://docs.djangoproject.com/en/1.7/topics/db/managers/#creating-manager-with-queryset-methods) which provides much the same benefits (DRY code through method copying, etc).

Because the `_PassThroughManager` is dynamic and locally scoped, rather than a module level class, I'm not sure of a fix beyond either migrating away to the aforementioned new functionality, or setting `use_in_migrations` to `False`.

**Comment by pacahon** [comment]
Thx for response.
