### ISSUE TITLE
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

### ISSUE THREAD

**Issue by hellvix** [carljm/django-model-utils#199]
user@thunder-linux:~/Dropbox/arq/dev/python/proejct$ pip install django-model-utils
Downloading/unpacking django-model-utils
  Downloading django-model-utils-2.4.tar.gz
  Running setup.py (path:/tmp/pip-build-lDjMff/django-model-utils/setup.py) egg_info for package django-model-utils
    
    warning: manifest_maker: MANIFEST.in, line 7: unknown action 'locale/*/LC_MESSAGES/django.po'
    
Downloading/unpacking Django>=1.4.2 (from django-model-utils)
  Downloading Django-1.9-py2.py3-none-any.whl (6.6MB): 6.6MB downloaded
Installing collected packages: django-model-utils, Django
  Running setup.py install for django-model-utils
    
    warning: manifest_maker: MANIFEST.in, line 7: unknown action 'locale/*/LC_MESSAGES/django.po'
    
Compiling /tmp/pip-build-lDjMff/Django/django/conf/app_template/apps.py ...
  File "/tmp/pip-build-lDjMff/Django/django/conf/app_template/apps.py", line 4
    class {{ camel_case_app_name }}Config(AppConfig):
          ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-lDjMff/Django/django/conf/app_template/models.py ...
  File "/tmp/pip-build-lDjMff/Django/django/conf/app_template/models.py", line 1
    {{ unicode_literals }}from django.db import models
                             ^
SyntaxError: invalid syntax

user@thunder-linux:~/Dropbox/arq/dev/python/project$ python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/user/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/home/user/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 176, in fetch_command
    commands = get_commands()
  File "/home/user/.local/lib/python2.7/site-packages/django/utils/lru_cache.py", line 100, in wrapper
    result = user_function(*args, **kwds)
  File "/home/user/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 71, in get_commands
    for app_config in reversed(list(apps.get_app_configs())):
  File "/home/user/.local/lib/python2.7/site-packages/django/apps/registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "/home/user/.local/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

#python --version
Python 2.7.10

#import Django
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ImportError: No module named Django
#import django
django.VERSION
(1, 9, 0, 'final', 0)

Problem also happens on Django 1.8.7.

**Comment by kezabelle** [comment]
Hi,
This is usually a result of accessing models before the internal Django machinery is complete - usually doing queries at module level, or before `AppConfig.ready()` is fired. Without seeing your models, it's near impossible to guess where the problem lies. What functionality from model-utils are you using? From your "steps taken" it's unclear.

At this stage, it's hard to know if it's a model-utils problem, unless you can demonstrate with a snippet or small reproducible project which functionality of model-utils is a problem (and I appreciate that may not be easy, because the `AppRegistryNotReady` exception is almost famously vague, unfortunately)

**Comment by hellvix** [comment]
That problem started when I installed django-model-utils. I didn't even get the chance to set it up. I installed then the problem started. It messed my Django installation, not even uninstalling the package with pip I got rid of the message. I had to reinstall Django and install all my packages again.

**Comment by carljm** [comment]
From the above log, it looks like when you installed django-model-utils, it also installed Django 1.9 as a dependency. It wouldn't have done that if you already had Django (1.4.2 or newer) installed. So my first question about "the problem started when I installed django-model-utils" is "with what version of Django was it working previously?" If it's something more recent than 1.4.2, then it seems you had it installed in a non-standard way where pip couldn't detect that it was already installed, thus installing 1.9.

Clearly there's something going on here beyond model-utils, because there is no way that model-utils itself could possibly cause this problem unless you modify your code base to import/use it. Based on your description, ISTM the most likely possibility is that installing model-utils caused your version of Django to be upgraded to 1.9, and that resulted in you seeing this error where you didn't before. The upgraded Django would take effect immediately after installation of model-utils (without changing your codebase to use model-utils) and would persist even after uninstalling model-utils. I can't think of any other effect that would have those characteristics.

If that's the case, then this isn't a bug in model-utils, it's just a matter of needing to pay more careful attention to dependency versions.

**Comment by hellvix** [comment]
I didn't have model-utils installed before, this was the very first time. I had Djang 1.8.6, then I installed this package and the problem occurred. I tried upgrading to Django 1.9 and got the same problem. 
My project wouldn't work until I reinstalled all other packages but model-utils. I have a huge code under models.py, posting everything here may be a bit complicated.
But if it happened as suggested by kezabelle, I will give it a look.

**Comment by carljm** [comment]
So it sounds to me like your problem is caused by the upgrade from Django 1.8.6 to 1.9, and is not related to model-utils (except in that installing model-utils caused an upgrade to 1.9, since for some reason pip couldn't see your 1.8.6 installation).

**Comment by hellvix** [comment]
Yeah, indeed. The problem lies on my code and the upgrade to 1.9. So the problem happens when queries are made in models.py?

**Comment by hellvix** [comment]
The problem was the new file called apps.py Python 1.9 installs. It should be also on my folder. It took me a few hours to figure this out.
