### ISSUE TITLE
InheritanceManagerMixin get_queryset not work with Manager.from_queryset  [Django 1.9]

### ISSUE THREAD

**Issue by root-shkim** [carljm/django-model-utils#205]
Since QuerySet._clone() has been changed at Djang 1.9,
https://github.com/django/django/commit/4c3bfe9053766d378999d06ec34ee5fd4e39f511#diff-5b0dda5eb9a242c15879dc9cd2121379R1043

InheritanceManagerMixin get_queryset always returns InheritanceQuerySet() because there is no 'klass'.

[Django < 1.9]
"c = klass(model=self.model, query=query, using=self._db, hints=self._hints)" clones new my Managers QuerySet.

However, at [Django 1.9]
"clone = self.__class__(model=self.model, query=query, using=self._db, hints=self._hints)" always clones InheritanceQuerySet.

So my Manager.from_queryset does not adapt.

**Comment by kezabelle** [comment]
Hi,
Are you using the latest PyPI release (2.4)? #192 was merged in November to fix that issue (ce8deed5cac7273a4a04555445eddda958f2fa5b), and should form part of the 2.4 release from December.

If you're not using the latest version, please try upgrading it to see if that resolves your issue. If you are using the latest version and it isn't working, please provide a minimal example of your code so it can be demonstrated how the previous fix missed a use-case.

**Comment by carljm** [comment]
Closing pending more information.

**Comment by root-shkim** [comment]
This is my sample code I attached.
when you access "/tests/get-queryset/" you can get 

'InheritanceQuerySet' object has no attribute 'created_by'
Request Method:	GET
Request URL:	http://localhost:8000/tests/get-queryset/
Django Version:	1.9.1
Exception Type:	AttributeError
Exception Value:	
'InheritanceQuerySet' object has no attribute 'created_by'

So I tried to fix this issue.
This bellow code works.
class InheritanceManagerMixin(object):
    use_for_related_fields = True
    def get_queryset(self):
        # return InheritanceQuerySet(self.model)
        return self._queryset_class(self.model)



[mysite.zip](https://github.com/carljm/django-model-utils/files/109296/mysite.zip)

**Comment by carljm** [comment]
What version of django-model-utils?

**Comment by root-shkim** [comment]
Django==1.9.1
django-model-utils==2.4

**Comment by carljm** [comment]
Your proposed "fix" would turn `InheritanceManagerMixin` into a no-op by default.

If you need to combine `InheritanceQuerySet` with another custom queryset, define your own manager that inherits `InheritanceManagerMixin`, and override its `get_queryset` method to return an instance of your own custom QuerySet class that inherits from `InheritanceQuerySetMixin`. See the note at the bottom of http://django-model-utils.readthedocs.org/en/latest/managers.html#mixins

**Comment by root-shkim** [comment]
I am sorry that I just uploaded my sample source code by ZIP file.

Could you please see below code?
https://gist.github.com/root-shkim/37e8395f94290012efa5

This custom manger `NodeManager` and queryset `NodeQueySet` inherit `InheritanceManagerMixin` and `NodeManager` overrides its get_queryset as well.

**Comment by carljm** [comment]
I see. The key information I was missing was that you are using `from_queryset()`. It's not changes to `clone` that are relevant here, it's that `InheritanceManager` was written before `from_queryset()` (and the `_queryset_class` class attribute) existed.

You can still make it work as-is, if you (as mentioned above) explicitly "return an instance of your own custom QuerySet class" from your `get_queryset` method, instead of calling `super()`. Your current `get_queryset` manager method just uses whatever queryset class is returned by `super()`, which will always be the basic `InheritanceQuerySet` given the current implementation of `InheritanceManager`.

But I would accept a PR to update `InheritanceManagerMixin` to respect `self._queryset_class` (and for `InheritanceManager` to have it set to `InheritanceQuerySet`).

**Comment by root-shkim** [comment]
It is better to explicitly return an instance of custom QuerySet class instead of calling `super()`.
Thanks @carljm for your kind.
