### ISSUE TITLE
Question about attribution

### ISSUE THREAD

**Issue by grantmcconnaughey** [carljm/django-model-utils#209]
@carljm I am almost finished with a Django package that tracks model field history and stores it in the database. I borrow heavily from `FieldTracker` to do this. [Here is my class](https://github.com/grantmcconnaughey/django-field-history/blob/master/field_history/tracker.py) in the app. Check out [the README](https://github.com/grantmcconnaughey/django-field-history/blob/master/README.rst) to get an idea of what it does.

I would like to know how you would like to be attributed in my app. Would you like a comment mentioning that the class is inspired by yours? Would you like a thanks in README.rst? Or should I add you to the copyright?

I'll hold off on deploying to PyPI until I hear from you. Thanks!

**Comment by carljm** [comment]
Thanks for checking! `FieldTracker` was actually authored by @treyhunner so I'd like his input. Personally I'd be quite happy to have your package take over that space, and remove `FieldTracker` from model-utils in favor of your version, so I don't have to maintain it anymore :-) IANAL but I think if you directly borrowed any code, Trey retains copyright on that code so you maybe should mention him in the copyright statement (though many projects just do a blanket "and contributors"). I think a README credit would probably be nice, but I'll let Trey speak to that.

**Comment by treyhunner** [comment]
:+1: for moving `FieldTracker` into its own project. I don't do much Django work right now and so I don't actually use `FieldTracker` myself currently. To that end, @grantmcconnaughey, you might want to add a compatibility layer or documentation on switching from django-model-utils' `FieldTracker` to your version.

As for credit/authorship: you're using the same license so there's no issue there, but you should credit the original authors in the AUTHORS file at least. There's a small handful of contributors ([a partial if not complete list is here](https://github.com/carljm/django-model-utils/blob/master/model_utils/tracker.py)).

I had a similar authorship/credit issue with django-simple-history when I declared my fork the official one. The previous author credited the original author in a section [within the AUTHORS file](https://github.com/treyhunner/django-simple-history/blob/master/AUTHORS.rst#background). Something like that would be fine. Since you're taking this from django-model-utils you might want to note that in the README both to credit myself and the original project and so that people understand the history of this code.

It looks like you have a lot of experience maintaining Django apps, but do feel free to reach out to me if you have questions about the project or maintaining it. I'm glad to see the code has found another good home. :smile_cat:

**Comment by grantmcconnaughey** [comment]
I honestly hadn't thought of completely moving `FieldTracker` functionality to my app. What mine does is similar but a little bit different. Where `FieldTracker` tells you which fields have changed since the model was created, `FieldHistoryTracker` stores those changes long-term. For instance, if you have a `PizzaOrder` model and you want a history of all the times the order's `status` has changed.

I suppose I could try to think of a way that I could combine both of the functionality and make the long-term storage thing optional? Or perhaps I could have both classes in my app and let the user choose which type of tracking they would like? What do you guys think, @treyhunner @carljm ?

**Comment by carljm** [comment]
I wasn't necessarily thinking your app had to provide an exact API-compatible replica of `FieldTracker` in order to provide a (long-term) migration path, as long as it was capable of covering the same use cases. I wouldn't remove `FieldTracker` from model-utils immediately, I'd first deprecate it for a long while and recommend your app as a replacement.

That said, I didn't realize until now that your app actually adds additional database queries to store the full history in a new `FieldHistory` model. I am guessing that might be a deal-breaker for some people currently using `FieldTracker` (it's something I'd be personally concerned about for performance reasons). So I think that unless django-field-history provided some option to avoid extra db access and just store the history of the current instance in-memory, I probably wouldn't consider it a replacement that would let me deprecate `FieldTracker`.

Which doesn't imply anything about what you should do, you're certainly under no obligation to replace `FieldTracker` :-)

**Comment by treyhunner** [comment]
:point_up: ditto what @carljm said. I also misunderstood what django-field-history was for.

It looks like this actually solves the same use case as [django-simple-history](https://django-simple-history.readthedocs.org/en/latest/usage.html#querying-history). Separately from the issue of giving credit, I'd be interested in cross-linking or possibly combining those projects if it makes sense to do so. You might want to list your project [on Django Packages also](https://www.djangopackages.com/grids/g/model-audit/). I'll move discussion about use case for this off of this issue though.

**Comment by carljm** [comment]
Closing this issue - I don't think there's anything else specific that needs to be addressed here. (Feel free to comment with further questions or thoughts, though.)
