### ISSUE TITLE
Using multiple fields in has_changed()

### ISSUE THREAD

**Issue by stantond** [carljm/django-model-utils#225]
Is `has_changed('field1', 'field2', 'field3')` supported? If so, could it be added to the docs please? If not, what do you think about adding this functionality?

**Comment by kezabelle** [comment]
As far as I can tell, it is not supported - the function signature expects only one fieldname. 

The bigger question about changing it to accept multiple, is what the actual test is. Does`has_changed('field1', 'field2')` = `True` if *all* the fields have changed, or if *any* of the fields have changed? Given it's not clear (to me) which would be correct, it seems to be me it'd be sensible to leave it in userland to check rather than in-library, as it's then explicit what's being tested. Potentially a docs update to show how one might do either of the above would be valuable ...

fwiw, the userland code I'm thinking of is something like: 
`all(obj.has_changed(field) for field in ('field1', 'field2'))` - substitute `all` for `any` for the other potential truthy answer.

**Comment by stantond** [comment]
Ah, very good point. Maybe just add that one line to the docs?
